### ISSUE TITLE
Error while executing pa-box:

### ISSUE THREAD

**Issue by HeathClose** [qbart/isometric-pixel-art#1]
Error: ( : 2) Procedure execution of gimp-image-undo-disable failed on invalid input arguments: Procedure 'gimp-image-undo-disable' has been called with an invalid ID for argument 'image'. Most likely a plug-in is trying to work on an image that doesn't exist any longer.

**Comment by qbart** [comment]
Hello, It's been a while since I've touched this project so I may need some time to debug this, but I will try to help you. Could you tell me which operating system do you use and which gimp version do you have?

**Comment by HeathClose** [comment]
Yes thank you
Mac OS 10.12.2
Gimp 2.8

**Comment by qbart** [comment]
HI there,

It was a quite challenge to reproduce the error, but I was able to do it.
For me the error is shown when you are trying to use the plugin without creating the image first.
In order to use plugin correctly you need to:

1. create blank image first
2. set your tool to pencil, and set pencil to Pixel type with size of 1

Then you should be able to use it. Let me know if your case is similar and if it works for you.

Cheers.
